name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # Cada 12 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # 1️Clonar el repositorio
      - uses: actions/checkout@v3

      # 2️Generar SVG con estilo y GIF animado
      - name: Generate Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: JuanCarlos92
          outputs: |
            output/snake.svg

            output/snake-dark.svg?palette=github-dark

            output/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3️Publicar en la rama 'output'
      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
